### ISSUE TITLE
Please support quarter-step adjustment.

### ISSUE THREAD

**Issue by Uhucream** [jlj/NativeDisplayBrightness#1] opened 2017-09-03 08:41 UTC
OS X supports quarter-step adjustment on internal monitor.
You can use it by pushing Shift+Option and F1 or F2.
In the same way,I want you to support quarter-step adjustment at this application.

**Like this↓**
<a href="https://imgur.com/QaBA0Um"><img src="https://i.imgur.com/QaBA0Um.gif" title="source: imgur.com" /></a>

In addition, if you use code of kfix's ddcctl, ddcctl can change volume and power control of external monitor.
So I also want you to do volume and power control.

**Comment by jlj** [comment] 2017-09-03 10:24
Hi @Uhucream, Nice enhancement! I will implement it in the coming days.

**Comment by Uhucream** [comment] 2017-09-03 11:33
@jlj Thank you for responding!
Oh,really?
I'm looking forward to release!

**Comment by jlj** [comment] 2017-09-03 21:35
Implemented in v0.0.7: https://github.com/jlj/NativeDisplayBrightness/releases/tag/v0.0.7

**Comment by Uhucream** [comment] 2017-09-04 06:38
@jlj Thank you!
Wow! I was surprised at your fast release!

**Comment by jlj** [comment] 2017-09-04 07:49
@Uhucream Please confirm that quarter-step brightness adjustment has the expected behavior, before I close this issue.

And regarding your edit about changing volume and power control of external monitor, it would be better to enter these as two new distinct enhancement requests (Btw I plan to add volume control in the future, but I need to put my hand on an external monitor supporting it first) . 😎

**Comment by Uhucream** [comment] 2017-09-04 14:54
@jlj Yes,it works well.
But internal monitor's shortcut of quarter-step is **Shift**+Option+F2(or F1) only.
This app has both Option or Shift+Option,so I wanna you to make it only **Shift** one.

Thank you!
I'm looking forward to the time.

**Comment by jlj** [comment] 2017-09-04 15:12
> But internal monitor's shortcut of quarter-step is Shift+Option+F2(or F1) only.
> This app has both Option or Shift+Option

This is on purpose, because on Apple extended keyboard pressing fn + option + shift + F1 / F2 is quite a gymnastic 😉
So doing `fn + option + F1 / F2` is simpler in some cases. Therefore the utility supports both. 😀

**Closed as completed** 2017-09-05 07:38 UTC
Labels: enhancement

**Comment by Uhucream** [comment] 2017-09-05 14:05
@jlj Ah,I see.
